# Generated by Django 5.1.7 on 2025-03-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='nil', max_length=20)),
                ('userpass', models.CharField(default='nil', max_length=20)),
                ('useremail', models.CharField(default='nil', max_length=20)),
                ('usermobi', models.CharField(default='nil', max_length=20)),
            ],
        ),
    ]
