# Generated by Django 5.1.7 on 2025-03-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='NIL', max_length=20)),
                ('user', models.CharField(default='NIL', max_length=20)),
                ('userUid', models.CharField(default='NIL', max_length=20)),
                ('userPass', models.CharField(default='NIL', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDate', models.DateField()),
                ('userTime', models.CharField(default='NIL', max_length=25)),
                ('userLon', models.CharField(default='NIL', max_length=50)),
                ('userLat', models.CharField(default='NIL', max_length=50)),
                ('userCheckIn', models.CharField(default='NIL', max_length=100)),
                ('userCheckOut', models.CharField(default='NIL', max_length=100)),
            ],
        ),
    ]
