# Generated by Django 5.1.7 on 2025-03-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcheck', '0002_rename_user_userdata_usermail'),
    ]

    operations = [
        migrations.CreateModel(
            name='userLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userLogin', models.CharField(default='NIL', max_length=25)),
            ],
        ),
    ]
