# Generated by Django 5.1.7 on 2025-03-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcheck', '0003_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='userLogOut',
            field=models.CharField(default='NIL', max_length=25),
        ),
        migrations.AddField(
            model_name='userlog',
            name='userLogOutT',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='userlog',
            name='userLoginT',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
