# Generated by Django 5.1.7 on 2025-03-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcheck', '0005_office_useratt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='userRole',
            field=models.CharField(default='NIL', max_length=30),
        ),
    ]
